### ISSUE TITLE
Python3 compatible...

### ISSUE THREAD

**Issue by domi84** [gawbul/pyEnsemblRest#16]
Hi there,
I wanted try your package, but it seems not compatible with python3:
```
from ensemblrest import EnsemblRest
Traceback (most recent call last):

  File "/home/domenico/anaconda3/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2910, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-a96b87cb274d>", line 1, in <module>
    from ensemblrest import EnsemblRest

  File "/home/domenico/.local/lib/python3.5/site-packages/ensemblrest/__init__.py", line 36, in <module>
    from .ensemblrest import EnsemblRest, EnsemblGenomeRest

  File "/home/domenico/.local/lib/python3.5/site-packages/ensemblrest/ensemblrest.py", line 119
    raise Exception, "mandatory param '%s' not specified" %(param)
                   ^
SyntaxError: invalid syntax
```
Maybe you should plan to do it, time is running ;) https://pythonclock.org/

EDIT: I saw just now that you have a PR for that. Maybe in the main time you can block the installation for python3 from pip

**Comment by bunop** [comment]
Hi. @Danilka has recently submitted pull request #15 in which Python 3 support is provided. We are waiting that @gawbul accepts new changes.

**Comment by Danilka** [comment]
@domi84 Done.
